name = "phstatic13"
compatibility_date = "2026-03-25"
main = "src/worker.ts"

[env.production]
route = "phstatic.com.br/*"
zone_id = ""
ENVIRONMENT = "production"
SECURE_HEADERS = "true"
CSP_ENABLED = "true"
HSTS_MAX_AGE = "63072000"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[build]
command = "npm run build"
watch_paths = ["src/**/*.{ts,tsx,css}"]
upload.format = "modules"

[[kv_namespaces]]
binding = "PROMO_DB"
id = "e67114ae9b9049369e029a7e557e4482"
